/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface WagerFactoryInterface extends ethers.utils.Interface {
  functions: {
    "createWager((bytes,bytes,bytes,bytes,bytes,string,address,address))": FunctionFragment;
    "registry()": FunctionFragment;
    "setWagerModule(string,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createWager",
    values: [
      {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        wagerModuleName: string;
        oracleModule: string;
        oracleSource: string;
      }
    ]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setWagerModule",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createWager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setWagerModule",
    data: BytesLike
  ): Result;

  events: {};
}

export class WagerFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: WagerFactoryInterface;

  functions: {
    createWager(
      params: {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        wagerModuleName: string;
        oracleModule: string;
        oracleSource: string;
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registry(overrides?: CallOverrides): Promise<[string]>;

    setWagerModule(
      name: string,
      wagerModuleAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createWager(
    params: {
      parties: BytesLike;
      partyOneWagerData: BytesLike;
      blockData: BytesLike;
      wagerOracleData: BytesLike;
      supplumentalWagerOracleData: BytesLike;
      wagerModuleName: string;
      oracleModule: string;
      oracleSource: string;
    },
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registry(overrides?: CallOverrides): Promise<string>;

  setWagerModule(
    name: string,
    wagerModuleAddr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createWager(
      params: {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        wagerModuleName: string;
        oracleModule: string;
        oracleSource: string;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registry(overrides?: CallOverrides): Promise<string>;

    setWagerModule(
      name: string,
      wagerModuleAddr: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    createWager(
      params: {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        wagerModuleName: string;
        oracleModule: string;
        oracleSource: string;
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registry(overrides?: CallOverrides): Promise<BigNumber>;

    setWagerModule(
      name: string,
      wagerModuleAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createWager(
      params: {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        wagerModuleName: string;
        oracleModule: string;
        oracleSource: string;
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setWagerModule(
      name: string,
      wagerModuleAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
