/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface EquityModuleInterface extends ethers.utils.Interface {
  functions: {
    "acceptCounterEquity(bytes,(bytes,bytes,bytes,bytes,bytes,bytes,bytes,bytes,uint8,address,address,address))": FunctionFragment;
    "acceptEquity(bytes)": FunctionFragment;
    "decodeParties(bytes)": FunctionFragment;
    "decodeWagerEquity(bytes)": FunctionFragment;
    "settleEquity((bytes,bytes,bytes,bytes,bytes,bytes,bytes,bytes,uint8,address,address,address),address)": FunctionFragment;
    "voidEquity((bytes,bytes,bytes,bytes,bytes,bytes,bytes,bytes,uint8,address,address,address))": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "acceptCounterEquity",
    values: [
      BytesLike,
      {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        partyTwoWagerData: BytesLike;
        equityData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        result: BytesLike;
        state: BigNumberish;
        wagerModule: string;
        oracleModule: string;
        oracleSource: string;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptEquity",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "decodeParties",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "decodeWagerEquity",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleEquity",
    values: [
      {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        partyTwoWagerData: BytesLike;
        equityData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        result: BytesLike;
        state: BigNumberish;
        wagerModule: string;
        oracleModule: string;
        oracleSource: string;
      },
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "voidEquity",
    values: [
      {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        partyTwoWagerData: BytesLike;
        equityData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        result: BytesLike;
        state: BigNumberish;
        wagerModule: string;
        oracleModule: string;
        oracleSource: string;
      }
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptCounterEquity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptEquity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decodeParties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decodeWagerEquity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleEquity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voidEquity", data: BytesLike): Result;

  events: {};
}

export class EquityModule extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: EquityModuleInterface;

  functions: {
    acceptCounterEquity(
      partyTwoEquityData: BytesLike,
      wager: {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        partyTwoWagerData: BytesLike;
        equityData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        result: BytesLike;
        state: BigNumberish;
        wagerModule: string;
        oracleModule: string;
        oracleSource: string;
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    acceptEquity(
      equityData: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    decodeParties(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string, string] & { partyOne: string; partyTwo: string }>;

    decodeWagerEquity(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [number, [string, string], BigNumber, [BigNumber, BigNumber]] & {
        style: number;
        ercContracts: [string, string];
        amount: BigNumber;
        ids: [BigNumber, BigNumber];
      }
    >;

    settleEquity(
      wager: {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        partyTwoWagerData: BytesLike;
        equityData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        result: BytesLike;
        state: BigNumberish;
        wagerModule: string;
        oracleModule: string;
        oracleSource: string;
      },
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    voidEquity(
      wager: {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        partyTwoWagerData: BytesLike;
        equityData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        result: BytesLike;
        state: BigNumberish;
        wagerModule: string;
        oracleModule: string;
        oracleSource: string;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  acceptCounterEquity(
    partyTwoEquityData: BytesLike,
    wager: {
      parties: BytesLike;
      partyOneWagerData: BytesLike;
      partyTwoWagerData: BytesLike;
      equityData: BytesLike;
      blockData: BytesLike;
      wagerOracleData: BytesLike;
      supplumentalWagerOracleData: BytesLike;
      result: BytesLike;
      state: BigNumberish;
      wagerModule: string;
      oracleModule: string;
      oracleSource: string;
    },
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  acceptEquity(
    equityData: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  decodeParties(
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<[string, string] & { partyOne: string; partyTwo: string }>;

  decodeWagerEquity(
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [number, [string, string], BigNumber, [BigNumber, BigNumber]] & {
      style: number;
      ercContracts: [string, string];
      amount: BigNumber;
      ids: [BigNumber, BigNumber];
    }
  >;

  settleEquity(
    wager: {
      parties: BytesLike;
      partyOneWagerData: BytesLike;
      partyTwoWagerData: BytesLike;
      equityData: BytesLike;
      blockData: BytesLike;
      wagerOracleData: BytesLike;
      supplumentalWagerOracleData: BytesLike;
      result: BytesLike;
      state: BigNumberish;
      wagerModule: string;
      oracleModule: string;
      oracleSource: string;
    },
    recipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  voidEquity(
    wager: {
      parties: BytesLike;
      partyOneWagerData: BytesLike;
      partyTwoWagerData: BytesLike;
      equityData: BytesLike;
      blockData: BytesLike;
      wagerOracleData: BytesLike;
      supplumentalWagerOracleData: BytesLike;
      result: BytesLike;
      state: BigNumberish;
      wagerModule: string;
      oracleModule: string;
      oracleSource: string;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptCounterEquity(
      partyTwoEquityData: BytesLike,
      wager: {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        partyTwoWagerData: BytesLike;
        equityData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        result: BytesLike;
        state: BigNumberish;
        wagerModule: string;
        oracleModule: string;
        oracleSource: string;
      },
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        number,
        string,
        string,
        string
      ] & {
        parties: string;
        partyOneWagerData: string;
        partyTwoWagerData: string;
        equityData: string;
        blockData: string;
        wagerOracleData: string;
        supplumentalWagerOracleData: string;
        result: string;
        state: number;
        wagerModule: string;
        oracleModule: string;
        oracleSource: string;
      }
    >;

    acceptEquity(
      equityData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    decodeParties(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string, string] & { partyOne: string; partyTwo: string }>;

    decodeWagerEquity(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [number, [string, string], BigNumber, [BigNumber, BigNumber]] & {
        style: number;
        ercContracts: [string, string];
        amount: BigNumber;
        ids: [BigNumber, BigNumber];
      }
    >;

    settleEquity(
      wager: {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        partyTwoWagerData: BytesLike;
        equityData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        result: BytesLike;
        state: BigNumberish;
        wagerModule: string;
        oracleModule: string;
        oracleSource: string;
      },
      recipient: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    voidEquity(
      wager: {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        partyTwoWagerData: BytesLike;
        equityData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        result: BytesLike;
        state: BigNumberish;
        wagerModule: string;
        oracleModule: string;
        oracleSource: string;
      },
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    acceptCounterEquity(
      partyTwoEquityData: BytesLike,
      wager: {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        partyTwoWagerData: BytesLike;
        equityData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        result: BytesLike;
        state: BigNumberish;
        wagerModule: string;
        oracleModule: string;
        oracleSource: string;
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    acceptEquity(
      equityData: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    decodeParties(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    decodeWagerEquity(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    settleEquity(
      wager: {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        partyTwoWagerData: BytesLike;
        equityData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        result: BytesLike;
        state: BigNumberish;
        wagerModule: string;
        oracleModule: string;
        oracleSource: string;
      },
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    voidEquity(
      wager: {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        partyTwoWagerData: BytesLike;
        equityData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        result: BytesLike;
        state: BigNumberish;
        wagerModule: string;
        oracleModule: string;
        oracleSource: string;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptCounterEquity(
      partyTwoEquityData: BytesLike,
      wager: {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        partyTwoWagerData: BytesLike;
        equityData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        result: BytesLike;
        state: BigNumberish;
        wagerModule: string;
        oracleModule: string;
        oracleSource: string;
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    acceptEquity(
      equityData: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    decodeParties(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    decodeWagerEquity(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    settleEquity(
      wager: {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        partyTwoWagerData: BytesLike;
        equityData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        result: BytesLike;
        state: BigNumberish;
        wagerModule: string;
        oracleModule: string;
        oracleSource: string;
      },
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    voidEquity(
      wager: {
        parties: BytesLike;
        partyOneWagerData: BytesLike;
        partyTwoWagerData: BytesLike;
        equityData: BytesLike;
        blockData: BytesLike;
        wagerOracleData: BytesLike;
        supplumentalWagerOracleData: BytesLike;
        result: BytesLike;
        state: BigNumberish;
        wagerModule: string;
        oracleModule: string;
        oracleSource: string;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
